version: '3'

services:
  postgresql:
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recipes_ecommerce
    ports:
      - "5434:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data